name: Liquibase Deploy

on:
  workflow_dispatch:

jobs:
  db-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test DB Connectivity with psql
        env:
          DB_HOST: ghrunr-teghprodne01-2-omb-higher-pe.te-gh-prod-northeurope-01-privatelink.maersk.io
          DB_PORT: 5403
          DB_NAME: postgres
          DB_USER: pgbigboss
          DB_PASS: 3jCQm9jaHNd6jPvVFa
        run: |
          echo "Checking DB connectivity..."
          PGPASSWORD="${DB_PASS}" psql \
            -h "${DB_HOST}" \
            -p "${DB_PORT}" \
            -U "${DB_USER}" \
            -d "${DB_NAME}" \
            -c "SELECT NOW();"

