name: Liquibase Deploy

on:
  workflow_dispatch:

jobs:
  runner-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "OS: $RUNNER_OS"
          echo "Arch: $RUNNER_ARCH"
          echo "Job: $GITHUB_JOB"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"

          echo "=== System Info ==="
          uname -a

          echo "=== Network Interfaces ==="
          ip a || ifconfig

          echo "=== DNS Resolution Test ==="
          nslookup $DB_HOST || dig $DB_HOST || true

